//--- OBJECT WRITE BEGIN ---
new GuiControl(InventoryGui) {
   profile = "GuiDefaultProfile";
   horizSizing = "right";
   vertSizing = "bottom";
   position = "0 0";
   extent = "640 480";
   minExtent = "8 2";
   visible = "1";

   new GuiWindowCtrl(InvWnd) {
      profile = "GuiWindowProfile";
      horizSizing = "right";
      vertSizing = "bottom";
      position = "118 83";
      extent = "500 400";
      minExtent = "8 2";
      visible = "1";
      text = "Inventory";
      maxLength = "255";
      resizeWidth = "0";
      resizeHeight = "0";
      canMove = "1";
      canClose = "1";
      canMinimize = "0";
      canMaximize = "0";
      minSize = "50 50";
      closeCommand = "canvas.popdialog(InventoryGui);";

      new GuiScrollCtrl() {
         profile = "GuiScrollProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "10 30";
         extent = "200 360";
         minExtent = "8 2";
         visible = "1";
         command = "InvWnd_Selectitem();";
         willFirstRespond = "1";
         hScrollBar = "dynamic";
         vScrollBar = "alwaysOn";
         constantThumbHeight = "0";
         childMargin = "0 0";
         rowHeight = "40";
         columnWidth = "30";

         new GuiTextListCtrl(InvWndItemList) {
            profile = "GuiTextListProfile";
            horizSizing = "right";
            vertSizing = "bottom";
            position = "1 1";
            extent = "183 2";
            minExtent = "8 2";
            visible = "1";
            command = "InvWnd_Selectitem();";
            enumerate = "0";
            resizeCell = "1";
            columns = "0 100";
            fitParentWidth = "1";
            clipColumnText = "0";
         };
      };
      new GuiButtonCtrl(InvWndUse) {
         profile = "GuiButtonProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "280 125";
         extent = "140 30";
         minExtent = "8 2";
         visible = "0";
         command = "InvWnd_Use();";
         text = "Use";
         groupNum = "-1";
         buttonType = "PushButton";
      };
      new GuiTextCtrl(InvWndPN) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "220 40";
         extent = "33 18";
         minExtent = "8 2";
         visible = "1";
         text = "Name :";
         maxLength = "255";
      };
      new GuiTextCtrl(InvWndPD) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "220 80";
         extent = "31 18";
         minExtent = "8 2";
         visible = "1";
         text = "Desc :";
         maxLength = "255";
      };
      new GuiTextCtrl(InvWndItemName) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "260 40";
         extent = "38 18";
         minExtent = "8 2";
         visible = "1";
         text = "<name>";
         maxLength = "255";
      };
      new GuiTextCtrl(InvWndItemDesc) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "260 80";
         extent = "65 18";
         minExtent = "8 2";
         visible = "1";
         text = "<description>";
         maxLength = "255";
      };
      new GuiTextCtrl(InvWndPA) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "220 60";
         extent = "43 18";
         minExtent = "8 2";
         visible = "1";
         text = "Amount :";
         maxLength = "255";
      };
      new GuiTextCtrl(InvWndItemAmount) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "270 60";
         extent = "47 18";
         minExtent = "8 2";
         visible = "1";
         text = "<amount>";
         maxLength = "255";
      };
      new GuiTextCtrl(InvWndPA1) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "220 160";
         extent = "26 18";
         minExtent = "8 2";
         visible = "0";
         text = "<A1>";
         maxLength = "255";
      };
      new GuiTextCtrl(InvWndPA3) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "220 200";
         extent = "26 18";
         minExtent = "8 2";
         visible = "0";
         text = "<A3>";
         maxLength = "255";
      };
      new GuiTextCtrl(InvWndPA2) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "220 180";
         extent = "26 18";
         minExtent = "8 2";
         visible = "0";
         text = "<A2>";
         maxLength = "255";
      };
      new GuiTextCtrl(InvWndPA4) {
         profile = "GuiTextProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "220 220";
         extent = "26 18";
         minExtent = "8 2";
         visible = "0";
         text = "<A4>";
         maxLength = "255";
      };
      new GuiTextEditCtrl(InvWndA1) {
         profile = "GuiTextEditProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "280 160";
         extent = "200 18";
         minExtent = "8 2";
         visible = "0";
         maxLength = "255";
         historySize = "0";
         password = "0";
         tabComplete = "0";
         sinkAllKeyEvents = "0";
      };
      new GuiTextEditCtrl(InvWndA2) {
         profile = "GuiTextEditProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "280 180";
         extent = "200 18";
         minExtent = "8 2";
         visible = "0";
         maxLength = "255";
         historySize = "0";
         password = "0";
         tabComplete = "0";
         sinkAllKeyEvents = "0";
      };
      new GuiTextEditCtrl(InvWndA3) {
         profile = "GuiTextEditProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "280 200";
         extent = "200 18";
         minExtent = "8 2";
         visible = "0";
         maxLength = "255";
         historySize = "0";
         password = "0";
         tabComplete = "0";
         sinkAllKeyEvents = "0";
      };
      new GuiTextEditCtrl(InvWndA4) {
         profile = "GuiTextEditProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "280 220";
         extent = "200 18";
         minExtent = "8 2";
         visible = "0";
         maxLength = "255";
         historySize = "0";
         password = "0";
         tabComplete = "0";
         sinkAllKeyEvents = "0";
      };
      new GuiBitmapButtonCtrl() {
         profile = "BlockButtonProfile";
         horizSizing = "left";
         vertSizing = "bottom";
         position = "390 370";
         extent = "100 25";
         minExtent = "8 2";
         visible = "1";
         command = "OpenCombineGui();";
         text = "Combine";
         groupNum = "-1";
         buttonType = "PushButton";
         bitmap = "base/client/ui/button2";
         lockAspectRatio = "0";
         alignLeft = "0";
         overflowImage = "0";
         mKeepCached = "0";
         mColor = "255 99 0 255";
      };
      new GuiBitmapButtonCtrl() {
         profile = "BlockButtonProfile";
         horizSizing = "left";
         vertSizing = "bottom";
         position = "290 370";
         extent = "100 25";
         minExtent = "8 2";
         visible = "1";
         command = "OpenIAGui();";
         text = "ItemAdmin";
         groupNum = "-1";
         buttonType = "PushButton";
         bitmap = "base/client/ui/button2";
         lockAspectRatio = "0";
         alignLeft = "0";
         overflowImage = "0";
         mKeepCached = "0";
         mColor = "255 255 0 255";
      };
      new GuiBitmapButtonCtrl(InvWndUse) {
         profile = "BlockButtonProfile";
         horizSizing = "left";
         vertSizing = "bottom";
         position = "300 100";
         extent = "100 25";
         minExtent = "8 2";
         visible = "1";
         command = "InvWnd_Use();";
         text = "Use";
         groupNum = "-1";
         buttonType = "PushButton";
         bitmap = "base/client/ui/button1";
         lockAspectRatio = "0";
         alignLeft = "0";
         overflowImage = "0";
         mKeepCached = "0";
         mColor = "99 255 99 255";
      };
      new GuiTextEditCtrl(InvWnd_GA) {
         profile = "GuiTextEditProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "415 252";
         extent = "50 18";
         minExtent = "8 2";
         visible = "1";
         maxLength = "255";
         historySize = "0";
         password = "0";
         tabComplete = "0";
         sinkAllKeyEvents = "0";
      };
      new GuiTextEditCtrl(InvWnd_GN) {
         profile = "GuiTextEditProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "265 252";
         extent = "150 18";
         minExtent = "8 2";
         visible = "1";
         maxLength = "255";
         historySize = "0";
         password = "0";
         tabComplete = "0";
         sinkAllKeyEvents = "0";
      };
      new GuiBitmapButtonCtrl(InvWnd_GB) {
         profile = "BlockButtonProfile";
         horizSizing = "left";
         vertSizing = "bottom";
         position = "210 250";
         extent = "50 20";
         minExtent = "8 2";
         visible = "1";
         command = "InvWnd_Give();";
         text = "Give";
         groupNum = "-1";
         buttonType = "PushButton";
         bitmap = "base/client/ui/button2";
         lockAspectRatio = "0";
         alignLeft = "0";
         overflowImage = "0";
         mKeepCached = "0";
         mColor = "99 0 255 255";
      };
      new GuiBitmapButtonCtrl(InvWnd_DB) {
         profile = "BlockButtonProfile";
         horizSizing = "left";
         vertSizing = "bottom";
         position = "210 275";
         extent = "50 20";
         minExtent = "8 2";
         visible = "1";
         command = "InvWnd_DropItem();";
         text = "Drop";
         groupNum = "-1";
         buttonType = "PushButton";
         bitmap = "base/client/ui/button2";
         lockAspectRatio = "0";
         alignLeft = "0";
         overflowImage = "0";
         mKeepCached = "0";
         mColor = "99 255 99 255";
      };
      new GuiTextEditCtrl(InvWnd_DTB) {
         profile = "GuiTextEditProfile";
         horizSizing = "right";
         vertSizing = "bottom";
         position = "265 275";
         extent = "64 18";
         minExtent = "8 2";
         visible = "1";
         maxLength = "255";
         historySize = "0";
         password = "0";
         tabComplete = "0";
         sinkAllKeyEvents = "0";
      };
   };
};
//--- OBJECT WRITE END ---
